In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules

import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/aishwaryamate/Datasets/main/Supermarket.csv')

In [3]:
df

    ID                 Products
0    1       Milk, bread, sauce
1    2  Milk, Tea powder, bread
2    3       Bread, Jam, Butter
3    4            Bread, Butter
4    5             Maggie,Sauce
5    6      Maggie,Cheese,Sauce
6    7      Maggie,Cheese,Sauce
7    8     Peanut butter, Bread
8    9      Coffee, Sugar, Milk
9   10              Coffee,Milk
10  11      Maggie,Cheese,Sauce
11  12       Bread, Jam, Butter
12  13            Butter,Cheese
13  14      Maggie,Cheese,Sauce
14  15            Maggie,Bread
15  16         Bread, Torch,Jam
16  17       Bread, Jam, Butter
17  18         Jam,Butter,Torch
18  19       Bread, Jam, Butter
19  20  CornFlakes, Milk, Bread

In [4]:
df = df.drop('ID',axis=1)

In [5]:
df

                   Products
0        Milk, bread, sauce
1   Milk, Tea powder, bread
2        Bread, Jam, Butter
3             Bread, Butter
4              Maggie,Sauce
5       Maggie,Cheese,Sauce
6       Maggie,Cheese,Sauce
7      Peanut butter, Bread
8       Coffee, Sugar, Milk
9               Coffee,Milk
10      Maggie,Cheese,Sauce
11       Bread, Jam, Butter
12            Butter,Cheese
13      Maggie,Cheese,Sauce
14            Maggie,Bread
15         Bread, Torch,Jam
16       Bread, Jam, Butter
17         Jam,Butter,Torch
18       Bread, Jam, Butter
19  CornFlakes, Milk, Bread

In [6]:
def split(text):
    return text.split(',')

In [7]:
a = 'Milk, bread, sauce'

In [8]:
split(a)

['Milk', ' bread', ' sauce']

In [9]:
items =list( df['Products'].apply(split))

In [10]:
items

[['Milk', ' bread', ' sauce'],
 ['Milk', ' Tea powder', ' bread'],
 ['Bread', ' Jam', ' Butter'],
 ['Bread', ' Butter'],
 ['Maggie', 'Sauce'],
 ['Maggie', 'Cheese', 'Sauce'],
 ['Maggie', 'Cheese', 'Sauce'],
 ['Peanut butter', ' Bread'],
 ['Coffee', ' Sugar', ' Milk'],
 ['Coffee', 'Milk'],
 ['Maggie', 'Cheese', 'Sauce'],
 ['Bread', ' Jam', ' Butter'],
 ['Butter', 'Cheese'],
 ['Maggie', 'Cheese', 'Sauce'],
 ['Maggie', 'Bread '],
 ['Bread', ' Torch', 'Jam'],
 ['Bread', ' Jam', ' Butter'],
 ['Jam', 'Butter', 'Torch'],
 ['Bread', ' Jam', ' Butter'],
 ['CornFlakes', ' Milk', ' Bread']]

In [11]:
te = TransactionEncoder()

In [12]:
endf = te.fit_transform(items)

In [13]:
te.columns_

[' Bread',
 ' Butter',
 ' Jam',
 ' Milk',
 ' Sugar',
 ' Tea powder',
 ' Torch',
 ' bread',
 ' sauce',
 'Bread',
 'Bread ',
 'Butter',
 'Cheese',
 'Coffee',
 'CornFlakes',
 'Jam',
 'Maggie',
 'Milk',
 'Peanut butter',
 'Sauce',
 'Torch']

In [14]:
endf

array([[False, False, False, False, False, False, False,  True,  True,
        False, False, False, False, False, False, False, False,  True,
        False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False,  True,
        False, False, False],
       [False,  True,  True, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False,
        False, False, False],
       [False,  True, False, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False,
        False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False,
        False,  True, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False,  True, False,
        False,  True, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False,  True, False,
        False,  True, False],
       [ True, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
         True, False, False],
       [False, False, False,  True,  True, False, False, False, False,
        False, False, False, False,  True, False, False, False, False,
        False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False,  True,
        False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False,  True, False,
        False,  True, False],
       [False,  True,  True, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False,
        False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False,  True,  True, False, False, False, False, False,
        False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False,  True, False,
        False,  True, False],
       [False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False, False, False,  True, False,
        False, False, False],
       [False, False, False, False, False, False,  True, False, False,
         True, False, False, False, False, False,  True, False, False,
        False, False, False],
       [False,  True,  True, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False,
        False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False,  True, False, False,
        False, False,  True],
       [False,  True,  True, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False,
        False, False, False],
       [ True, False, False,  True, False, False, False, False, False,
        False, False, False, False, False,  True, False, False, False,
        False, False, False]])

In [15]:
data = pd.DataFrame(data=endf,columns=te.columns_)

In [16]:
data

,Bread,Butter,Jam,Milk,Sugar,Tea powder,Torch,bread,sauce,Bread,...,Butter,Cheese,Coffee,CornFlakes,Jam,Maggie,Milk,Peanut butter,Sauce,Torch
0,False,False,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,True,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
2,False,True,True,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
5,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,True,False,False,True,False
6,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,True,False,False,True,False
7,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
8,False,False,False,True,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,True,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,True,False,False,True,False
11,False,True,True,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,True,False,False,True,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
15,False,False,False,False,False,False,True,False,False,True,...,False,False,False,False,True,False,False,False,False,False
16,False,True,True,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,True,False,False,False,False,True
18,False,True,True,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
19,True,False,False,True,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False

In [17]:
data.replace(False,0,inplace=True)
data.replace(True,1,inplace=True)

In [18]:
data

,Bread,Butter,Jam,Milk,Sugar,Tea powder,Torch,bread,sauce,Bread,...,Butter,Cheese,Coffee,CornFlakes,Jam,Maggie,Milk,Peanut butter,Sauce,Torch
0,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
2,0,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
5,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
6,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
7,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
8,0,0,0,1,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
11,0,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
15,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
16,0,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,1
18,0,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
19,1,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [19]:
ap = apriori(data,min_support=0.2,use_colnames=True)

In [20]:
ap

    support                 itemsets
0      0.25                ( Butter)
1      0.20                   ( Jam)
2      0.30                  (Bread)
3      0.25                 (Cheese)
4      0.30                 (Maggie)
5      0.25                  (Sauce)
6      0.20          ( Jam,  Butter)
7      0.25         ( Butter, Bread)
8      0.20            ( Jam, Bread)
9      0.20         (Cheese, Maggie)
10     0.20          (Sauce, Cheese)
11     0.25          (Sauce, Maggie)
12     0.20   ( Jam,  Butter, Bread)
13     0.20  (Sauce, Cheese, Maggie)

In [21]:
model = association_rules(ap,metric='confidence')

In [22]:
model

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,( Jam),( Butter),0.20,0.25,0.20,1.000000,4.000000,0.1500,inf
1,( Butter),( Jam),0.25,0.20,0.20,0.800000,4.000000,0.1500,4.00
2,( Butter),(Bread),0.25,0.30,0.25,1.000000,3.333333,0.1750,inf
3,(Bread),( Butter),0.30,0.25,0.25,0.833333,3.333333,0.1750,4.50
4,( Jam),(Bread),0.20,0.30,0.20,1.000000,3.333333,0.1400,inf
5,(Cheese),(Maggie),0.25,0.30,0.20,0.800000,2.666667,0.1250,3.50
6,(Sauce),(Cheese),0.25,0.25,0.20,0.800000,3.200000,0.1375,3.75
7,(Cheese),(Sauce),0.25,0.25,0.20,0.800000,3.200000,0.1375,3.75
8,(Sauce),(Maggie),0.25,0.30,0.25,1.000000,3.333333,0.1750,inf
9,(Maggie),(Sauce),0.30,0.25,0.25,0.833333,3.333333,0.1750,4.50
10,"( Jam, Butter)",(Bread),0.20,0.30,0.20,1.000000,3.333333,0.1400,inf
11,"( Jam, Bread)",( Butter),0.20,0.25,0.20,1.000000,4.000000,0.1500,inf
12,"( Butter, Bread)",( Jam),0.25,0.20,0.20,0.800000,4.000000,0.1500,4.00
13,( Jam),"( Butter, Bread)",0.20,0.25,0.20,1.000000,4.000000,0.1500,inf
14,( Butter),"( Jam, Bread)",0.25,0.20,0.20,0.800000,4.000000,0.1500,4.00
15,"(Sauce, Cheese)",(Maggie),0.20,0.30,0.20,1.000000,3.333333,0.1400,inf
16,"(Sauce, Maggie)",(Cheese),0.25,0.25,0.20,0.800000,3.200000,0.1375,3.75
17,"(Cheese, Maggie)",(Sauce),0.20,0.25,0.20,1.000000,4.000000,0.1500,inf
18,(Sauce),"(Cheese, Maggie)",0.25,0.20,0.20,0.800000,4.000000,0.1500,4.00
19,(Cheese),"(Sauce, Maggie)",0.25,0.25,0.20,0.800000,3.200000,0.1375,3.75

# Thank You!